Repository QualityUnit/flowhunt-theme, pull requests merged in 2024-11, with the labels that each got.

#137 [3194] FlowHunt - related articles
  assets/styles/components/_SimilarSources.scss
Labels: status:review-OK

#138 [3264] fix: spacing between glossary elements
  assets/styles/components/Index.scss
Labels: action:needs-review

#148 [3285] new footer
  assets/images/flowhunt-logo_white.svg
  assets/images/footer_banner_gradient.svg
  assets/styles/common/_animations.scss
  assets/styles/common/_variables.scss
  assets/styles/components/_BlockDark.scss
  assets/styles/components/compactHeader.scss
  assets/styles/elements/_Button.scss
  assets/styles/layouts/Elementor.scss
  assets/styles/layouts/Footer.scss
  assets/styles/layouts/_FooterTopBanner.scss
  composer.lock
  lib/components/post-sidebar.php
  templates/content-archive-features.php
  templates/content-archive-flow-templates.php
  templates/content-archive-tools.php
  templates/content-archive-videos.php
  templates/content-single-features.php
  templates/footer-top-banner.php
  templates/footer.php
  templates/newsletter-form.php
Labels: action:needs-review

#150 [3252] feat: new cta banner
  lib/functions/widgets.php
  lib/widgets/cta-banner/block.json
  lib/widgets/cta-banner/cta-banner.php
  lib/widgets/cta-banner/images/block-cta-right-img.jpg
  lib/widgets/cta-banner/images/block-improve-bg.jpg
  lib/widgets/cta-banner/index.php
  lib/widgets/cta-banner/layouts/banner.php
  lib/widgets/cta-banner/package.json
  lib/widgets/cta-banner/src/index.js
  lib/widgets/cta-banner/src/layouts/frontend/CTABanner.jsx
  lib/widgets/cta-banner/src/scss/_Button.scss
  lib/widgets/cta-banner/src/scss/editor.scss
  lib/widgets/cta-banner/src/scss/style.scss
  lib/widgets/cta-banner/yarn.lock
  lib/widgets/improve-banner/images/block-improve-right-img.png
  lib/widgets/improve-banner/improve-banner.php
  lib/widgets/improve-banner/layouts/banner.php
  lib/widgets/improve-banner/src/index.js
  lib/widgets/improve-banner/src/layouts/frontend/ImproveBanner.jsx
  lib/widgets/improve-banner/src/scss/_Button.scss
  lib/widgets/improve-banner/src/scss/editor.scss
  package.json
Labels: status:review-OK

#149 [1036] enterprise pricing
  assets/images/icon-arrow.svg
  assets/images/icon_checkmark_cross.svg
  assets/images/icon_checkmark_primary.svg
  assets/scripts/custom/pricingNew.js
  assets/scripts/custom/responsiveTable.js
  assets/styles/Elementor.scss
  assets/styles/common/_global.scss
  assets/styles/common/_variables.scss
  assets/styles/components/BlockLinks.scss
  assets/styles/components/Table.scss
  assets/styles/components/_ComparePlansNew.scss
  assets/styles/components/_PricingPrograms.scss
  assets/styles/components/compactHeader.scss
  assets/styles/elements/_Button.scss
  assets/styles/elements/_Checklist.scss
  assets/styles/elements/_Switcher.scss
  assets/styles/elements/_Typography.scss
  assets/styles/layouts/_Posts.scss
  assets/styles/pages/Pricing.scss
  lib/functions/component-imports.php
  lib/helpers.php
  lib/pagesources.php
Labels: status:done, status:review-OK

#146 [3193] 3215 3216 fixes
  assets/images/quote.svg
  assets/styles/common/_mixins.scss
  assets/styles/layouts/_BlogPost.scss
  author.php
  lib/custom-blocks/compact-header.php
  templates/content-single.php
Labels: status:review-OK

#152 [3292] fix: missing image references
  templates/content-single-features.php
  templates/content-single-flow-templates.php
Labels: action:needs-review

#153 [3293] fix: youtube video
  .github/scripts/build-zip.sh
  assets/styles/layouts/Post.scss
Labels: status:review-OK

#154 [3233] fix: multiple improvements to cls, schema
  assets/images/compact-header-ai-tools.png
  assets/images/compact-header-features.png
  assets/images/compact-header-glossary.png
  assets/images/compact-header-templates.png
  assets/styles/components/compactHeader.scss
  page.php
  templates/content-archive.php
  templates/content-single-features.php
  templates/content-single-flow-templates.php
  templates/content-single-glossary.php
  templates/content-single-kb.php
  templates/content-single-tools.php
  templates/content-single-videos.php
  templates/head.php
Labels: action:needs-review

#155 fix: table javascript
  assets/scripts/custom/responsiveTable.js
  assets/styles/pages/Pricing.scss
Labels: action:needs-review

#157 [1330] The Chat Bubble of the new design of chatbot should be smaller
  base-scripts.php
Labels: status:review-OK
