Repository QualityUnit/flowhunt-theme, pull requests merged in 2024-08, with the labels that each got.

#49 [3081] article type page
  assets/images/facebook.svg
  assets/scripts/custom/data-scroll.js
  assets/scripts/custom/sidebar_toc.js
  assets/styles/app.scss
  assets/styles/common/_global.scss
  assets/styles/common/_mixins.scss
  assets/styles/common/_variables.scss
  assets/styles/components/BlockImprove.scss
  assets/styles/components/ImproveBanner.scss
  assets/styles/components/PostSidebar.scss
  assets/styles/components/SidebarTOC.scss
  assets/styles/components/_RelatedArticles.scss
  assets/styles/components/_SignupForm-sidebar.scss
  assets/styles/elements/_Typography.scss
  assets/styles/layouts/Post.scss
  composer.lock
  lib/components/post-sidebar.php
  lib/functions/component-imports.php
  lib/functions/sidebar-toc.php
  lib/post-types/flow-templates.php
  lib/shortcodes/sidebar-banner.php
  lib/taxonomies/flow-templates-categories.php
  lib/widgets/improve-banner/images/block-improve-bg.jpg
  lib/widgets/improve-banner/images/block-improve-right-img.png
  lib/widgets/improve-banner/images/modules_stack.png
  lib/widgets/improve-banner/improve-banner.php
  lib/widgets/improve-banner/layouts/banner.php
  lib/widgets/improve-banner/src/index.js
  lib/widgets/improve-banner/src/layouts/frontend/ImproveBanner.jsx
  lib/widgets/improve-banner/src/scss/editor.scss
  lib/widgets/improve-banner/src/scss/style.scss
  package.json
  template-blog-header.php
  template-blog.php
  templates/content-page.php
  templates/content-single-features.php
  templates/content-single-flow-templates.php
  templates/content-single-glossary.php
  templates/content-single-kb.php
  templates/content-single-videos.php
  templates/content-single.php
  yarn.lock
Labels: action:needs-review

#50 [3089] Flowhunt web - Redesign old list type page
  assets/images/compact-header-dots.jpg
  assets/images/compact-header-features-img.png
  assets/images/compact-header-templates-img.png
  assets/scripts/custom/compactHeader.js
  assets/styles/components/compactHeader.scss
  assets/styles/elements/_Breadcrumb.scss
  assets/styles/pages/Pricing.scss
  lib/custom-blocks/compact-header.php
  templates/content-archive-features.php
  templates/content-archive-flow-templates.php
  templates/content-single-features.php
  templates/content-single-flow-templates.php
Labels: status:done, status:review-OK

#51 [3081] feat: related articles as separate component with args
  assets/styles/app.scss
  assets/styles/components/RelatedArticles.scss
  lib/components/related-articles.php
  templates/content-single-features.php
  templates/content-single-flow-templates.php
  templates/content-single.php
Labels: status:done, status:review-OK

#52 [3081] fix: post sidebar
  assets/styles/components/PostSidebar.scss
  assets/styles/components/_ScrollTrigger.scss
  assets/styles/layouts/Post.scss
Labels: action:needs-review

#53 Posts in homepage
  assets/scripts/custom/filter.js
  assets/styles/common/_global.scss
  assets/styles/common/_gridLayout.scss
  assets/styles/components/ElementorBlogPosts.scss
  assets/styles/components/_ScrollTrigger.scss
  lib/shortcodes.php
  lib/shortcodes/elementor-blog-posts.php
Labels: action:needs-review

#56 [3090] Wrong header size on FlowHunt
  assets/styles/common/_typography.scss
  assets/styles/elements/_Button.scss
Labels: action:needs-review

#59 feat: new header, scroll block on mobile static
  assets/scripts/custom/data-scroll.js
  assets/styles/components/_HeroSectionLanding.scss
  assets/styles/components/_ScrollTrigger.scss
Labels: action:changes-requested

#61 [3110] feat: glossary and headers fix
  assets/images/article_title_h3_bg.svg
  assets/images/compact-header-glossary.png
  assets/styles/components/compactHeader.scss
  assets/styles/elements/_PostTypography.scss
  assets/styles/elements/_SearchField.scss
  lib/components/related-articles.php
  lib/components/searchfield.php
  lib/functions/redirects.php
  lib/setup.php
  lib/taxonomies/glossary-categories.php
  templates/content-archive-glossary.php
  templates/content-single-glossary.php
  templates/content-single.php
Labels: action:needs-review

#62 I3107 fixes scroll header
  assets/scripts/custom/data-scroll.js
  assets/styles/components/_HeroSectionLanding.scss
  assets/styles/components/_ScrollTrigger.scss
Labels: action:needs-review

#63 [3112] fix: wrappers width
  assets/styles/common/_mixins.scss
Labels: action:needs-review

#64 [3088] Lists not working on all webs
  assets/styles/elements/_PostTypography.scss
Labels: action:needs-review

#65 [3113] Visual Improvement for AI Chatbot
  assets/styles/components/_BlockImage.scss
Labels: action:needs-review

#66 [3117] fix: compact header progress bar position
  assets/scripts/custom/compactHeader.js
Labels: action:needs-review

#67 [3108[ fix: features filtering
  assets/scripts/custom/filter.js
Labels: action:needs-review

#68 [3124] fix: slider for images in articles
  assets/styles/components/RelatedArticles.scss
  assets/styles/elements/_Typography.scss
  lib/custom-blocks/compact-header.php
Labels: action:needs-review

#69 [3125] fix: filtering not working on mobiles
  assets/scripts/custom/filter.js
  assets/styles/components/Filter.scss
  assets/styles/components/_Form.scss
  assets/styles/components/compactHeader.scss
  assets/styles/elements/_FilterMenu.scss
  assets/styles/elements/_Inputs.scss
  assets/styles/elements/_SearchField.scss
  assets/styles/elements/_SortingMenu.scss
  assets/styles/layouts/Header.scss
  base-scripts.php
  lib/assets.php
  lib/custom-blocks/compact-header.php
  lib/functions/component-imports.php
Labels: action:needs-review

#70 [3129] Align image to bottom of the postype headers
  assets/styles/components/compactHeader.scss
Labels: action:needs-review

#71 [3122] feat: redesigned elements for ai chatbot page
  assets/scripts/custom/compactHeader.js
  assets/styles/Elementor.scss
  assets/styles/common/_global.scss
  assets/styles/common/_mixins.scss
  assets/styles/components/BlockImprove.scss
  assets/styles/components/BlockVideo.scss
  assets/styles/components/SidebarTOC.scss
  assets/styles/components/Table.scss
  assets/styles/components/UrlslabTOC.scss
  assets/styles/components/_BlockImage.scss
  assets/styles/components/_BlockWithVideoBottom.scss
  assets/styles/components/_CookieBar.scss
  assets/styles/components/_HeroBanner.scss
  assets/styles/components/compactHeader.scss
  assets/styles/elements/_Checklist.scss
  assets/styles/elements/_FilterMenu.scss
  assets/styles/elements/_Typography.scss
  assets/styles/layouts/Post.scss
  assets/styles/layouts/SignUpAndLogin.scss
  lib/functions/component-imports.php
Labels: action:needs-review

#72 [3130] Fix some visual bugs on the mobile devices
  assets/styles/common/_global.scss
  assets/styles/common/elementor-custom.scss
  assets/styles/components/_BlockFullWidthBackground.scss
  assets/styles/components/_HeroSection.scss
  assets/styles/components/_HeroSectionLanding.scss
  assets/styles/components/compactHeader.scss
  assets/styles/elements/_Button.scss
  assets/styles/layouts/Footer.scss
  assets/styles/layouts/Header.scss
  assets/styles/shortcodes/PostsInfinitySlider.scss
Labels: action:needs-review

#73 [3115] lorem impsum text flowhunt web page
  templates/content-archive-flow-templates.php
Labels: action:needs-review

#74 [3132] Change the newsletter subscription link in the footer form
  templates/newsletter-form.php
Labels: action:needs-review

#77 [3121] Redesign archives pages on the flowhunt website
  assets/images/default-icon-features.svg
  assets/images/features-card-background-dots.jpg
  assets/styles/components/_HeroSectionLanding.scss
  assets/styles/components/compactHeader.scss
  assets/styles/elements/_FilterMenu.scss
  assets/styles/elements/_SearchField.scss
  assets/styles/layouts/_Posts.scss
  lib/metaboxes/features.php
  lib/metaboxes/flow-templates.php
  lib/shortcodes/posts-infinity-slider.php
  templates/content-archive-features.php
  templates/content-archive-flow-templates.php
Labels: action:needs-review

#80 [3142] Fix blurry image on AI chatbot page
  functions.php
Labels: action:needs-review

#79 [3138] Blog page layout is broken with 5 articles (FlowHunt)
  assets/styles/components/BlogTopPost.scss
  assets/styles/layouts/_Blog.scss
  assets/styles/pages/blog.scss
  templates/content-archive.php
Labels: status:done, status:review-OK

#82 [3139] Longer headings overlap with thumbnails (FlowHunt)
  assets/styles/components/compactHeader.scss
  lib/custom-blocks/compact-header.php
  templates/content-archive-features.php
  templates/content-archive-flow-templates.php
  templates/content-archive.php
  templates/content-single-features.php
  templates/content-single-flow-templates.php
Labels: status:done, status:review-OK

#84 [3153] Align footer menu to the right side
  assets/styles/layouts/Footer.scss
Labels: status:done, status:review-OK

#85 [3154] Add gap between sections in the Pricing
  assets/styles/components/_PricingPrograms.scss
Labels: status:done, status:review-OK

#86 [3121] Aligned icons on the features archive
  assets/styles/layouts/_Posts.scss
Labels: action:needs-review

#87 [3152] Fixed heading styles if the heading is a link
  assets/styles/components/_BlockBoxes.scss
Labels: action:needs-review

#90 Fixed some visual bugs on archives
  assets/styles/layouts/_Posts.scss
  templates/content-archive-flow-templates.php
Labels: status:done, status:review-OK

#89 [3508] FH / jumping of content during scrolling
  assets/styles/components/compactHeader.scss
Labels: action:needs-review

#88 [3148] Rearranged css files for single post pages
  assets/styles/layouts/Post.scss
  lib/components/post-sidebar.php
Labels: action:needs-review

#91 [3160] CTA Button not working in Blog, Template Post types
  lib/shortcodes/sidebar-banner.php
Labels: action:needs-review

#94 [3520] FH web / ReferenceError: trialButton is not defined
  base-scripts.php
Labels: status:review-OK

#93 [3167] Anchor is almost invisible on dark background - FlowHunt Homepage
  assets/styles/components/_BlockFullWidthBackground.scss
Labels: status:done, status:review-OK

#92 [3151] Improvements for Related Flow
  assets/styles/components/RelatedArticles.scss
  lib/components/related-articles.php
Labels: status:done, status:review-OK
