Repository QualityUnit/flowhunt-theme, pull requests merged in 2024-10, with the labels that each got.

#120 [3196] Search in template page redirect incorrectly
  assets/scripts/custom/filter.js
  assets/styles/layouts/_Posts.scss
  lib/custom-blocks/compact-header.php
  templates/content-archive-features.php
  templates/content-archive-flow-templates.php
  templates/content-archive-glossary.php
  templates/content-archive-tools.php
  templates/content-archive-videos.php
Labels: action:needs-review

#126 [3166] CTA not working properly on FlowHunt from Elementor
  lib/functions.php
  lib/functions/customize-gutenberg-button.php
Labels: status:ready-to-merge, status:review-OK

#127 [3223] New chatbot with new integration code for whole website
  base-scripts.php
Labels: status:review-OK

#128 [3243] i3181 blog
  assets/images/compact-header-dots.jpg
  assets/images/header-dots.png
  assets/scripts/custom/blogLazyLoad.js
  assets/styles/common/_typography.scss
  assets/styles/components/BlogTopPost.scss
  assets/styles/components/compactHeader.scss
  assets/styles/layouts/_ArchiveColumns.scss
  assets/styles/layouts/_Blog.scss
  gulpfile.mjs
  lib/cleaner/assets.php
  lib/custom-blocks/compact-header.php
  lib/functions.php
  lib/functions/rest-api.php
  lib/rest-api/get-blog-posts.php
  lib/setup.php
  templates/content-archive.php
  templates/content-single.php
Labels: action:needs-review, status:review-OK

#131 [943] aitools header
  assets/images/compact-header-ai-tools.png
  assets/images/compact-header-templates-img.png
  assets/images/features-card-background-dots.jpg
  assets/images/features-post-header-bg.png
  assets/images/post_item_header-background-dots.png
  assets/styles/components/compactHeader.scss
  assets/styles/layouts/_Posts.scss
  lib/custom-blocks/compact-header.php
  lib/metaboxes.php
  lib/metaboxes/flow-templates.php
  lib/metaboxes/tools.php
  templates/content-archive-features.php
  templates/content-archive-flow-templates.php
  templates/content-archive-tools.php
  templates/content-single-flow-templates.php
  templates/content-single-tools.php
Labels: action:needs-review

#130 [3212] fix: ai tools archive
  assets/images/compact-header-features-img.png
  assets/images/compact-header-features.png
  assets/images/compact-header-templates-img.png
  assets/images/compact-header-templates.png
  assets/styles/components/Index.scss
  assets/styles/components/compactHeader.scss
  base-scripts.php
  lib/custom-blocks/compact-header.php
  templates/content-archive-features.php
  templates/content-archive-flow-templates.php
  templates/content-archive-glossary.php
  templates/glossary-index.php
Labels: action:needs-review

#132 [3245] Multiple PHP Warning related to Related Article
  lib/components/related-articles.php
Labels: action:needs-review

#134 [3254] fix: small design fixes
  assets/images/checkbox-active.svg
  assets/images/checkbox-hover.svg
  assets/images/checkbox-inactive.svg
  assets/styles/common/_mixins.scss
  assets/styles/components/Index.scss
  assets/styles/components/compactHeader.scss
  assets/styles/elements/_Breadcrumb.scss
  assets/styles/elements/_FilterMenu.scss
  assets/styles/elements/_Inputs.scss
  assets/styles/elements/_SearchField.scss
  assets/styles/layouts/_Posts.scss
  lib/components/searchfield.php
  lib/custom-blocks/compact-header.php
  templates/content-archive-glossary.php
Labels: action:needs-review

#135 [3256] FH web - add related resources to all pages of all post types
  lib/functions.php
  lib/functions/urlslab-related-posts.php
  templates/content-single-features.php
  templates/content-single-flow-templates.php
  templates/content-single-glossary.php
  templates/content-single-tools.php
  templates/content-single.php
Labels: action:needs-review

#133 [3255] fix: sidebar try banner text changes
  lib/shortcodes/sidebar-banner.php
Labels: action:needs-review
