Repository QualityUnit/flowhunt-theme, pull requests merged in 2025-01, with the labels that each got.

#178 [3295] fix margin on pricing page
  assets/styles/common/_mixins.scss
  assets/styles/pages/Pricing.scss
Labels: action:needs-review

#179 [3301] - fix: added styles for self-hosted label on pricing page
  assets/styles/components/_PricingPrograms.scss
Labels: action:needs-review

#186 [3312] fix: some components additional styling
  assets/styles/common/_marginsPaddings.scss
  assets/styles/common/_typography.scss
  assets/styles/components/ImageSwitcher.scss
  assets/styles/components/_BlockDark.scss
Labels: status:done, status:review-OK

#187 [3329] fix: blog posts lazy loading
  assets/scripts/app/custom_lightbox_youtube.js
  assets/scripts/custom/blogLazyLoad.js
  assets/styles/common/_lightbox.scss
  assets/styles/components/_BlockDark.scss
  assets/styles/layouts/_Blog.scss
  lib/shortcodes/elementor-blog-posts.php
Labels: action:needs-review

#188 [3330] feat: fixes for mobile
  assets/scripts/custom/responsiveTable.js
  assets/styles/common/_marginsPaddings.scss
  assets/styles/common/_variables.scss
  assets/styles/components/ImageSwitcher.scss
  assets/styles/components/_HeroSectionLanding.scss
  assets/styles/components/_Table.scss
  assets/styles/elements/_Typography.scss
  assets/styles/shortcodes/Clients.scss
  composer.lock
Labels: action:needs-review

#189 [3327] feat: created page Solutions - Business (added styles for button)
  assets/images/tabler-icon-arrow-up-right.svg
  assets/styles/elements/_Button.scss
Labels: status:done, status:review-OK

#190 fix: condition for icons in table
  assets/scripts/custom/responsiveTable.js
Labels: action:needs-review

#192 [3242] new menu
  assets/images/menu_tour-card.png
  assets/scripts/app/copyCodeBlock.js
  assets/scripts/app/custom_lightbox_youtube.js
  assets/styles/common/_global.scss
  assets/styles/common/_variables.scss
  assets/styles/components/ImageSwitcher.scss
  assets/styles/components/_BlockDark.scss
  assets/styles/components/_CodeBlock.scss
  assets/styles/elements/Header/_HeaderNavigationMain.scss
  assets/styles/elements/Header/_HeaderNavigationSubMenu.scss
  composer.lock
  gulpfile.mjs
  lib/cleaner/assets.php
  lib/functions.php
  lib/functions/custom-main-menu.php
  templates/header.php
Labels: action:needs-review

#194 [3336] fix: prompt code
  assets/styles/components/_CodeBlock.scss
  assets/styles/elements/_Typography.scss
Labels: action:needs-review

#195 [3309] ai training landing page
  assets/images/icon-brain.svg
  assets/images/icon-cost.svg
  assets/images/icon-productivity.svg
  assets/scripts/app/custom_lightbox_youtube.js
  assets/styles/Elementor.scss
  assets/styles/common/_colorClasses.scss
  assets/styles/common/_variables.scss
  assets/styles/components/_BannerLandingBlock.scss
  assets/styles/components/_BenefitsBlock.scss
  assets/styles/components/_HeroSectionLanding.scss
  assets/styles/components/_Labels.scss
  assets/styles/components/_TrainingCourseBlock.scss
  assets/styles/shortcodes/Clients.scss
  lib/assets.php
  lib/metaboxes.php
  lib/metaboxes/clients.php
  lib/metaboxes/success-stories.php
  lib/post-types.php
  lib/post-types/services.php
  lib/post-types/solutions.php
  lib/shortcodes/clients.php
  lib/shortcodes/success-stories.php
  templates/content-single-services.php
  templates/content-single-solutions.php
Labels: action:needs-review

#196 [3236] - fix: removed block script for lazy-load where we have sidebar-toc
  assets/scripts/custom/sidebar_toc.js
Labels: action:needs-review

#193 [3242] fix: icon animation
  assets/scripts/custom/responsiveTable.js
  assets/styles/common/_variables.scss
  assets/styles/elements/Header/_HeaderNavigationMain.scss
  assets/styles/elements/Header/_HeaderNavigationSubMenu.scss
  base.php
  lib/functions.php
  lib/functions/custom-main-menu.php
Labels: action:needs-review

#197 [3337] fix: adding overlay for mobile
  assets/styles/components/_BlockChecklist.scss
Labels: action:needs-review

#198 [3309] - fix: changes styles for AI-Training page
  assets/styles/components/_BannerLandingBlock.scss
  assets/styles/components/_BenefitsBlock.scss
  assets/styles/components/_HeroSectionLanding.scss
  assets/styles/components/_TrainingCourseBlock.scss
  assets/styles/shortcodes/Clients.scss
Labels: status:review-OK

#199 fix: few minor css tweaks
  assets/styles/elements/Header/_HeaderNavigationSubMenu.scss
  assets/styles/elements/_Button.scss
Labels: status:review-OK

#201 [3344] - fix: changed tag h3 to div and added style for it
  assets/styles/elements/Header/_HeaderNavigationSubMenu.scss
  lib/functions/custom-main-menu.php
Labels: status:done, status:review-OK

#203 [3309] ai training update design
  assets/images/icon-arrow-down.svg
  assets/images/icon-globe-gradient.svg
  assets/images/icone-play-gradient.svg
  assets/styles/Elementor.scss
  assets/styles/components/_Labels.scss
  assets/styles/components/_TrainingCourseAnchors.scss
  assets/styles/components/_TrainingCourseBlock.scss
Labels: action:needs-review

#200 [3298] homepage fixes
  assets/images/flow_modular-ai_mobile.svg
  assets/styles/Elementor.scss
  assets/styles/components/_BlockChecklist.scss
  assets/styles/components/_CookieBar.scss
  assets/styles/components/_FlowModular.scss
  assets/styles/components/_HeroBanner.scss
  assets/styles/components/_HeroSectionLanding.scss
  assets/styles/components/_SolutionsBlock.scss
  assets/styles/components/_WavyLines.scss
  assets/styles/elements/_Button.scss
  assets/styles/elements/_Typography.scss
  assets/styles/layouts/Footer.scss
  assets/styles/layouts/_FooterTopBanner.scss
  templates/footer-top-banner.php
  templates/footer.php
  templates/newsletter-form.php
Labels: action:needs-review

#202 [3253]: Fix /ai-tools/simple-chatbot-google-search-template/
  assets/styles/components/compactHeader.scss
Labels: status:review-OK
