Repository QualityUnit/flowhunt-theme, pull requests merged in 2025-03, with the labels that each got.

#228 [1598] - enhancement of pricing table
  assets/images/icon-star-blue-border.svg
  assets/images/icon-star-blue-full.svg
  assets/styles/components/_PricingPrograms.scss
  assets/styles/pages/Pricing.scss
Labels: action:needs-review

#221 [3361] - solution home page bugs
  assets/styles/common/_typography.scss
  assets/styles/common/_variables.scss
  assets/styles/components/ElementorBlogPosts.scss
  assets/styles/components/_BlockDark.scss
  assets/styles/components/_FAQ.scss
  assets/styles/components/_FlowModular.scss
  assets/styles/components/_HeroBanner.scss
  assets/styles/components/_HeroSectionLanding.scss
  assets/styles/components/_SolutionsBlock.scss
  assets/styles/elements/_Typography.scss
Labels: action:needs-review

#229 [3345] - quote element for flowhunt blog article fix
  assets/styles/common/_variables.scss
  assets/styles/layouts/Post.scss
  assets/styles/layouts/_BlogPost.scss
  lib/widgets/chatbot-output/src/scss/style.scss
  lib/widgets/tip/src/scss/style.scss
  package.json
Labels: status:done, status:review-OK

#231 fix: replaced correct gtag id
  base-scripts.php
Labels: action:needs-review

#232 [3379] feat: adding trial info to pricing page
  assets/styles/elements/_LabelTag.scss
  assets/styles/pages/Pricing.scss
Labels: action:changes-requested

#230 [3345] - fix: updated styles for lists and changed timeline block
  assets/images/icon_checkmark_primary_big.svg
  assets/styles/layouts/_BlogPost.scss
  lib/widgets/timeline-item/layouts/timeline.php
  lib/widgets/timeline-item/src/layouts/frontend/TimelineItem.jsx
  lib/widgets/timeline/layouts/timeline.php
Labels: action:needs-review

#235 [3350] - ai agents page
  assets/styles/Elementor.scss
  assets/styles/common/_variables.scss
  assets/styles/components/BlockVideo.scss
  assets/styles/components/_BlockDark.scss
  assets/styles/components/_BlockLink.scss
  assets/styles/components/_HeroBanner.scss
  assets/styles/elements/_Typography.scss
Labels: action:needs-review

#236 [3345] - fix: small change for images and lists
  assets/styles/layouts/Post.scss
  assets/styles/layouts/_BlogPost.scss
Labels: action:needs-review

#237 [3367] - feat: created Services page
  assets/styles/Elementor.scss
  assets/styles/common/_variables.scss
  assets/styles/components/_BannerLandingBlock.scss
  assets/styles/components/_BlockIcons.scss
  assets/styles/components/_BlockWithLabels.scss
  assets/styles/components/_HeroBanner.scss
  assets/styles/components/_HeroSectionLanding.scss
  assets/styles/components/_Labels.scss
Labels: action:needs-review

#239 [3363] - menu small fixes
  assets/scripts/app/app.js
  assets/styles/elements/Header/_HeaderNavigationMain.scss
  assets/styles/elements/Header/_HeaderNavigationSubMenu.scss
  lib/functions/custom-main-menu.php
Labels: action:needs-review

#241 [3381] - fix: fixed black line on video on "The future of AI is modular"
  assets/styles/components/_FlowModular.scss
Labels: status:done, status:review-OK

#240 [3350] - fix: fixed media queries and small styles on AI Agents page
  assets/styles/components/_BlockLink.scss
  assets/styles/components/_HeroBanner.scss
Labels: action:needs-review
